default_language_version:
  python: python
exclude: ^\.precommit_appdata/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        types: [python]

        additional_dependencies: [
          "django-stubs",
          "dj-database-url",
          "Django>=5,<6",
          "djangorestframework>=3.15,<4",
          "pytest>=8.2,<9",
          "pytest-django>=4.8,<5",
          "celery>=5.4,<6"
        ]
        args: ["--config-file=pyproject.toml"]
