name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          python -m ruff check .
          python -m ruff format --check .
      - name: Type check
        run: |
          python -m mypy --strict --ignore-missing-imports .
      - name: Tests
        run: |
          python manage.py migrate --noinput
          pytest -q


